import { describe, expect, it } from 'vitest';
import {
  buildStructureSql,
  columnDefinition,
  countByPhase,
  EMPTY_ROWS,
  idempotentIndex,
  introspectionQueries,
  PHASE_ORDER,
  replaceableTrigger,
  sequenceResetSql,
  type ColumnRow,
  type StructureRows,
} from './structure.ts';

const ALL = PHASE_ORDER;

function column(over: Partial<ColumnRow> = {}): ColumnRow {
  return {
    table_name: 'clients',
    schema: 'public',
    column_name: 'id',
    data_type: 'uuid',
    not_null: true,
    default_expr: null,
    identity: '',
    generated: '',
    position: 1,
    ...over,
  };
}

function rows(over: Partial<StructureRows> = {}): StructureRows {
  return { ...EMPTY_ROWS, ...over };
}

describe('introspectionQueries', () => {
  it('borne chaque requête au schéma demandé, en littéral protégé', () => {
    const queries = introspectionQueries("l'autre");
    for (const query of queries) {
      if (query.key === 'extensions') continue; // les extensions sont globales
      expect(query.sql).toContain("'l''autre'");
    }
  });

  it('écarte ce qui appartient à une extension', () => {
    const byKey = new Map(
      introspectionQueries('public').map(q => [q.key, q.sql])
    );
    expect(byKey.get('functions')).toContain("d.deptype = 'e'");
    expect(byKey.get('columns')).toContain("dp.deptype = 'e'");
  });

  it('demande un relevé, pas une modification', () => {
    for (const query of introspectionQueries('public')) {
      expect(query.sql.trim().toLowerCase().startsWith('select')).toBe(true);
    }
  });
});

describe('columnDefinition', () => {
  it('écrit type, défaut et non-nullité', () => {
    expect(
      columnDefinition(
        column({ default_expr: 'gen_random_uuid()', not_null: true })
      )
    ).toBe('"id" uuid default gen_random_uuid() not null');
  });

  it("écrit l'identité au lieu du défaut", () => {
    expect(
      columnDefinition(
        column({ data_type: 'bigint', identity: 'a', default_expr: null })
      )
    ).toBe('"id" bigint generated always as identity not null');
    expect(
      columnDefinition(column({ data_type: 'bigint', identity: 'd' }))
    ).toContain('generated by default as identity');
  });

  it('écrit une colonne calculée avec son expression', () => {
    expect(
      columnDefinition(
        column({
          column_name: 'total',
          data_type: 'numeric',
          generated: 's',
          default_expr: '(prix * quantite)',
          not_null: false,
        })
      )
    ).toBe('"total" numeric generated always as ((prix * quantite)) stored');
  });

  it('protège un nom de colonne exotique', () => {
    expect(columnDefinition(column({ column_name: 'année' }))).toContain(
      '"année"'
    );
  });
});

describe('idempotentIndex', () => {
  it('insère IF NOT EXISTS', () => {
    expect(
      idempotentIndex('CREATE INDEX idx ON public.t USING btree (a)')
    ).toBe('CREATE INDEX if not exists idx ON public.t USING btree (a)');
    expect(idempotentIndex('CREATE UNIQUE INDEX u ON t (a)')).toContain(
      'if not exists'
    );
  });

  it('ne le met pas deux fois', () => {
    const once = idempotentIndex('CREATE INDEX IF NOT EXISTS i ON t (a)');
    expect(once).toBe('CREATE INDEX IF NOT EXISTS i ON t (a)');
  });
});

describe('replaceableTrigger', () => {
  it('rend un déclencheur remplaçable', () => {
    expect(
      replaceableTrigger('CREATE TRIGGER t BEFORE INSERT ON x FOR EACH ROW ...')
    ).toContain('create or replace trigger ');
  });

  it('refuse un déclencheur de contrainte, non remplaçable', () => {
    expect(
      replaceableTrigger('CREATE CONSTRAINT TRIGGER t AFTER INSERT ON x ...')
    ).toBeNull();
  });
});

describe('buildStructureSql', () => {
  it('range les instructions dans l’ordre des phases', () => {
    const statements = buildStructureSql(
      rows({
        columns: [column()],
        extensions: [{ name: 'pgcrypto', schema: 'extensions' }],
        grants: [
          { table_name: 'clients', privileges: 'SELECT', grantee: 'anon' },
        ],
        constraints: [
          {
            table_name: 'clients',
            schema: 'public',
            name: 'clients_pkey',
            type: 'p',
            definition: 'PRIMARY KEY (id)',
          },
        ],
      }),
      { schema: 'public', phases: ALL }
    );
    expect(statements.map(s => s.phase)).toEqual([
      'extension',
      'table',
      'constraint',
      'grant',
    ]);
  });

  it('crée les clés primaires avant les clés étrangères', () => {
    const statements = buildStructureSql(
      rows({
        constraints: [
          {
            table_name: 'commandes',
            schema: 'public',
            name: 'fk_client',
            type: 'f',
            definition: 'FOREIGN KEY (client_id) REFERENCES clients(id)',
          },
          {
            table_name: 'clients',
            schema: 'public',
            name: 'clients_pkey',
            type: 'p',
            definition: 'PRIMARY KEY (id)',
          },
        ],
      }),
      { schema: 'public', phases: ALL }
    );
    expect(statements.map(s => s.object)).toEqual([
      'clients.clients_pkey',
      'commandes.fk_client',
    ]);
  });

  it('rend les contraintes et les politiques rejouables', () => {
    const statements = buildStructureSql(
      rows({
        constraints: [
          {
            table_name: 'clients',
            schema: 'public',
            name: 'c',
            type: 'c',
            definition: 'CHECK (age > 0)',
          },
        ],
        policies: [
          {
            schema: 'public',
            table_name: 'clients',
            name: 'lecture',
            permissive: 'PERMISSIVE',
            roles: '{anon,authenticated}',
            cmd: 'SELECT',
            qual: 'true',
            with_check: null,
          },
        ],
      }),
      { schema: 'public', phases: ALL }
    );
    for (const statement of statements) {
      expect(statement.sql).toContain('duplicate_object');
    }
    const policy = statements.find(s => s.phase === 'policy');
    expect(policy?.sql).toContain('to "anon", "authenticated"');
    expect(policy?.sql).toContain('for select');
    expect(policy?.sql).toContain('using (true)');
    expect(policy?.sql).not.toContain('with check');
  });

  it('active la RLS, et la force quand la source la force', () => {
    const statements = buildStructureSql(
      rows({
        rls: [
          { table_name: 'a', schema: 'public', enabled: true, forced: false },
          { table_name: 'b', schema: 'public', enabled: true, forced: true },
        ],
      }),
      { schema: 'public', phases: ALL }
    );
    expect(statements[0]?.sql).toContain('enable row level security');
    expect(statements[0]?.sql).not.toContain('force row level security');
    expect(statements[1]?.sql).toContain('force row level security');
  });

  it('n’écrit que les phases demandées', () => {
    const statements = buildStructureSql(
      rows({
        columns: [column()],
        policies: [
          {
            schema: 'public',
            table_name: 'clients',
            name: 'p',
            permissive: 'PERMISSIVE',
            roles: [],
            cmd: 'ALL',
            qual: null,
            with_check: null,
          },
        ],
      }),
      { schema: 'public', phases: ['table'] }
    );
    expect(statements).toHaveLength(1);
    expect(statements[0]?.phase).toBe('table');
  });

  it('se limite aux tables sélectionnées', () => {
    const statements = buildStructureSql(
      rows({
        columns: [column(), column({ table_name: 'secrets' })],
      }),
      { schema: 'public', phases: ALL, tables: ['clients'] }
    );
    expect(statements).toHaveLength(1);
    expect(statements[0]?.object).toBe('public.clients');
  });

  it('assemble un CREATE TABLE lisible et rejouable', () => {
    const statements = buildStructureSql(
      rows({
        columns: [
          column({ default_expr: 'gen_random_uuid()' }),
          column({ column_name: 'email', data_type: 'text', position: 2 }),
        ],
      }),
      { schema: 'public', phases: ['table'] }
    );
    const sql = statements[0]?.sql ?? '';
    expect(sql).toContain('create table if not exists "public"."clients"');
    expect(sql).toContain('"id" uuid default gen_random_uuid() not null');
    expect(sql).toContain('"email" text not null');
  });

  it('écrit les libellés d’énumération en littéraux protégés', () => {
    const statements = buildStructureSql(
      rows({
        enums: [{ name: 'etat', schema: 'public', labels: ["l'un", 'deux'] }],
      }),
      { schema: 'public', phases: ['type'] }
    );
    expect(statements[0]?.sql).toContain("'l''un', 'deux'");
  });
});

describe('sequenceResetSql', () => {
  it('remet à niveau les colonnes à séquence, et elles seules', () => {
    const statements = sequenceResetSql([
      column({ column_name: 'id', data_type: 'bigint', identity: 'd' }),
      column({
        column_name: 'num',
        default_expr: "nextval('t_num_seq'::regclass)",
      }),
      column({ column_name: 'email', data_type: 'text' }),
    ]);
    expect(statements.map(s => s.object)).toEqual([
      'clients.id',
      'clients.num',
    ]);
    expect(statements[0]?.sql).toContain('setval(');
    expect(statements[0]?.sql).toContain('is not null');
  });

  it('respecte la sélection de tables', () => {
    expect(sequenceResetSql([column({ identity: 'a' })], ['autre'])).toEqual(
      []
    );
  });
});

describe('countByPhase', () => {
  it('compte par phase, dans l’ordre d’exécution', () => {
    const statements = buildStructureSql(
      rows({
        columns: [column(), column({ table_name: 'z' })],
        extensions: [{ name: 'pgcrypto', schema: 'extensions' }],
      }),
      { schema: 'public', phases: ALL }
    );
    expect(countByPhase(statements)).toEqual([
      { phase: 'extension', label: 'Extensions', count: 1 },
      { phase: 'table', label: 'Tables', count: 2 },
    ]);
  });
});
